# Generated by Django 3.1 on 2020-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
